### ISSUE TITLE
是否可以不自动打牌，而是给出打牌建议，这样有助于学习bot的打法？

### ISSUE THREAD

**Issue by ayssia** [Jimboom7/AlphaJong#42]
如题。

**Comment by yangruihan** [comment]
我制作了一个辅助模式，可以显示当前AI策略，而不是自动操作。你可以随时在界面上进行 AUTO 和 HELP 模式切换。

代码分支在这里：https://github.com/yangruihan/AlphaJong/tree/help_mode

你可以直接使用 https://github.com/yangruihan/AlphaJong/blob/help_mode/build/AlphaJong_1.2.2.user.js

我会尝试提 PR 合并到主干

<img width="455" alt="截屏2022-05-03 下午2 07 52" src="https://user-images.githubusercontent.com/7806458/166411206-836d62d4-4aaf-4076-9e88-f5ed31c361c5.png">

---------

I've made an "HELP" mode that shows the current AI strategy, instead of doing it automatically, you can switch between "AUTO" and "HELP" modes on the interface at any time.

The sources code branch is here:  https://github.com/yangruihan/AlphaJong/tree/help_mode

You can use https://github.com/yangruihan/AlphaJong/blob/help_mode/build/AlphaJong_1.2.2.user.js directly

I will try to make a PR.

<img width="455" alt="截屏2022-05-03 下午2 07 52" src="https://user-images.githubusercontent.com/7806458/166411206-836d62d4-4aaf-4076-9e88-f5ed31c361c5.png">

**Comment by yangruihan** [comment]
你也可以通过 F12 打开控制台，查看 AI 输出，其中有当前策略结果，以及手牌排名，你可以可以通过修改`LOG_AMOUNT`参数来展示更多的手牌排名结果

You can also open the console through F12 and view the AI output, which includes the current strategy results and the hand ranking. You can display more hand ranking results by modifying the `LOG_AMOUNT` parameter.

**Comment by yangruihan** [comment]
I've made a PR #43

**Comment by yangruihan** [comment]
其中：

|英文|中文|
|:---|:---|
|discard|弃牌|
|call|鸣|
|riichi|立直|
|kan|杠|

**Comment by Jimboom7** [comment]
This feature is now released in [version 1.3.0](https://github.com/Jimboom7/AlphaJong/releases/tag/v1.3.0). Thank you very much yangruihan!
