### ISSUE TITLE
Why calculateScore use the different rule?

### ISSUE THREAD

**Issue by murphymeng** [Jimboom7/AlphaJong#66]
If han is 7, the score should be 12000, not 14000. why calculateScore use below rule? The result is different from the real score.

```javascript
function calculateScore(player, han, fu = 30) {
	var score = (fu * Math.pow(2, 2 + han) * 4);

	if (han > 4) {
		score = 8000;
	}

	if (han > 5) {
		score = 8000 + ((han - 5) * 4000);
	}
	if (han > 6) {
		score = 12000 + ((han - 6) * 2000);
	}
	if (han > 8) {
		score = 16000 + ((han - 8) * 2666);
	}
	if (han > 11) {
		score = 24000 + ((han - 11) * 4000);
	}
	if (han >= 13) {
		score = 32000;
	}

	if (getSeatWind(player) == 1) { //Is Dealer
		score *= 1.5;
	}

	if (getNumberOfPlayers() == 3) {
		score *= 0.75;
	}

	return score;
}
```

**Comment by Jimboom7** [comment]
As the comment at the function says: _For higher han values the score is "fluid" to better account for situations where the exact han value is unknown_
For example: Opponent A is expected to have 6 han. Opponent B is expected to have 7 han. If the score would be calculated by hard numbers they would have the same expected score, but that's not good. Opponent B is more dangerous since we are not sure about the exact amount of han he has - maybe there is some hidden dora and it turns into a Baiman.
Same for the own hand: There are always some hidden factors, like Uradora, Haitei/Houtei or Tsumo. With the function above the bot is more likely to choose a hand with 7 han instead of 6 han.
