### ISSUE TITLE
Use simulated mouse clicks at specified coordinates instead of sending commands

### ISSUE THREAD

**Issue by WangZP10969** [Jimboom7/AlphaJong#82]
I've been using your script recently and it works perfectly.
I'm wondering if it's possible to simulate mouse click events at some specified locations instead of sending commands to make the process look more normal.

For example, after the game is over, wait for a fixed time, click the OK button to return to the home page, and click on the rank field for the next match, even in the game, click to realize the operation of the game.

I don't know scripting, just some ideas.

**Comment by HoruakutiX** [comment]
Agreed.
Actually, it is nearly an inevitable problem that the majsoul website often crash in CN sever when the game is over and the bot refresh it.
The error code is usually 404 or 403 and it can not be solved by using vpn, so it makes the bot can not be used for long time without human check.
I highly recommend that the bot can use clicking to start new game automaticly.
In addition, I guess it will be more difficult for yostar to ban the bot after using clicking instead of  sending commands.
